### ISSUE TITLE
Build failing on vercel after last commit

### ISSUE THREAD

**Issue by Vozf** [burhan-syed/troddit#174]
```
<html>
<body>
<!--StartFragment-->

TypeError: Cannot read properties of undefined (reading 'value')
--
11:11:44.841 | at useClerkNextOptions (/vercel/path0/node_modules/@clerk/nextjs/dist/cjs/client-boundary/NextOptionsContext.js:40:14)
11:11:44.841 | at SignIn (/vercel/path0/node_modules/@clerk/nextjs/dist/cjs/client-boundary/uiComponents.js:49:95)
11:11:44.841 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
11:11:44.841 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
11:11:44.841 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
11:11:44.841 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
11:11:44.841 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
11:11:44.841 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
11:11:44.841 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
11:11:44.841 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
11:11:44.841 |  
11:11:44.841 | Error occurred prerendering page "/sign-in/[[...index]]". Read more: https://nextjs.org/docs/messages/prerender-error
11:11:44.841 | TypeError: Cannot read properties of undefined (reading 'value')
11:11:44.842 | at useClerkNextOptions (/vercel/path0/node_modules/@clerk/nextjs/dist/cjs/client-boundary/NextOptionsContext.js:40:14)
11:11:44.842 | at SignIn (/vercel/path0/node_modules/@clerk/nextjs/dist/cjs/client-boundary/uiComponents.js:49:95)
11:11:44.842 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
11:11:44.842 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
11:11:44.842 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
11:11:44.842 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
11:11:44.842 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
11:11:44.842 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
11:11:44.842 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
11:11:44.842 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

<!--EndFragment-->
</body>
</html>
```
btw there's also a node16 eol warning
```
<html>
<body>
<!--StartFragment-->



Error: Node.js version 16.x has reached End-of-Life. Deployments created on or after 2023-08-15 will fail to build. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.
Expand 225 Lines
11:11:44.841

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by burhan-syed** [comment]
this is fixed now. 
How are you deploying to vercel? The node version should be changed in the project settings. If you're using the Docker config I need to update that.
