### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/forEach' is not defined by "exports" in /app/node_modules/ramda/package.json

### ISSUE THREAD

**Issue by Joshndroid** [burhan-syed/troddit#68]
I just updated about 30 minutes ago after having my docker working just fine for weeks, with taking in all updates.
My last update was yesterday afternoon prior to now.

I am getting 502 errors for some reason.
Nothing else has changed.

I had a look in the logs and see this fairly often.

Node.js v18.4.0
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/forEach' is not defined by "exports" in /app/node_modules/ramda/package.json
    at new NodeError (node:internal/errors:388:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:488:36)
    at Module._findPath (node:internal/modules/cjs/loader:528:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/forEach' is not defined by "exports" in /app/node_modules/ramda/package.json
    at new NodeError (node:internal/errors:388:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:488:36)
    at Module._findPath (node:internal/modules/cjs/loader:528:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by Joshndroid** [comment]
Having a google around is the docker npm version not exactly what your running on your dev system? hence it working for your dev updates and broken on my docker install suddenly (esp with all the theme/updates)

**Comment by Joshndroid** [comment]
Looking also at - https://www.npmjs.com/package/foreach

i tried to install foreach via the 'npm i foreach' via the console however nil permission to do so, which is fine but wondering if that needs to be put into the dockerfile to install it on docker start?

**Comment by Joshndroid** [comment]
Thanks mate
Just waiting for the dockhub to pull in the update and I'll be back to scrolling in no time
It's the best reddit fronted by far

**Comment by burhan-syed** [comment]
For sure, thanks for opening the issue and glad you enjoy troddit
