### ISSUE TITLE
Server error  There is a problem with the server configuration.  Check the server logs for more information.

### ISSUE THREAD

**Issue by X4Q4x6yf** [burhan-syed/troddit#94]
I've got troddit set up on my own server.  I works fine until I login.    I've created the secret and still get this error.

[next-auth][error][NO_SECRET] 

https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.

    at assertConfig (/app/node_modules/next-auth/core/lib/assert.js:42:12)

    at NextAuthHandler (/app/node_modules/next-auth/core/index.js:70:52)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async NextAuthNextHandler (/app/node_modules/next-auth/next/index.js:23:19)

    at async /app/node_modules/next-auth/next/index.js:59:32

    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)

    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)

    at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)

    at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32)

    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:600:29) {

  code: 'NO_SECRET'

**Comment by burhan-syed** [comment]
Are you're providing a [NEXTAUTH_SECRET](https://next-auth.js.org/configuration/options#nextauth_secret)  environment variable?

**Comment by codeyourwaytofreedom** [comment]
> Are you're providing a [NEXTAUTH_SECRET](https://next-auth.js.org/configuration/options#nextauth_secret) environment variable?

thanks Sir
